=== jorgy343/NovahTracer/Source/Novah.Tracer.Client/Scenes/Scene.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
    elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Root Element -->
  <xs:element name="Scene">
    <xs:complexType>
      <xs:all>

        <xs:element name="Camera" minOccurs="1">
          <xs:complexType>
            <xs:choice>
              <xs:element name="PerspectiveCamera" type="PerspectiveCamera" />
              <xs:element name="OrthographicCamera" type="OrthographicCamera" />
            </xs:choice>
          </xs:complexType>
        </xs:element>

        <xs:element name="Materials" minOccurs="0">
          <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element name="BasicMaterial" type="BasicMaterial" />
              <xs:element name="LuaMaterial" type="LuaMaterial" />
            </xs:choice>
          </xs:complexType>
        </xs:element>

        <xs:element name="Lights" minOccurs="0">
          <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element name="PointLight" type="PointLight" />
              <xs:element name="DirectionalLight" type="DirectionalLight" />
            </xs:choice>
          </xs:complexType>
        </xs:element>

        <xs:element name="RootSurface" minOccurs="1">
          <xs:complexType>
            <xs:group ref="GroupOfSurfaces" minOccurs="0" maxOccurs="1" />
          </xs:complexType>
        </xs:element>

      </xs:all>
      
      <xs:attribute name="BackgroundColor" type="Color3" use="required" />
      <xs:attribute name="DefaultRefractionIndex" type="xs:float" use="required" />
      <xs:attribute name="AntialiasingLevel" type="xs:integer" use="required" />
      
    </xs:complexType>
  </xs:element>

  <!-- Basic Types -->
  <xs:simpleType name="Color3">
    <xs:restriction base="xs:string">
      <xs:pattern value="\s*([+-]?[0-9]+\.?[0-9]*)\s*,\s*([+-]?[0-9]+\.?[0-9]*)\s*,\s*([+-]?[0-9]+\.?[0-9]*)\s*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Vector3">
    <xs:restriction base="xs:string">
      <xs:pattern value="\s*([+-]?[0-9]+\.?[0-9]*)\s*,\s*([+-]?[0-9]+\.?[0-9]*)\s*,\s*([+-]?[0-9]+\.?[0-9]*)\s*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Vector4">
    <xs:restriction base="xs:string">
      <xs:pattern value="\s*([+-]?[0-9]+\.?[0-9]*)\s*,\s*([+-]?[0-9]+\.?[0-9]*)\s*,\s*([+-]?[0-9]+\.?[0-9]*)\s*,\s*([+-]?[0-9]+\.?[0-9]*)\s*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Name">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z_][a-zA-Z0-9_]*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="MatrixStack">
    <xs:choice minOccurs="1" maxOccurs="unbounded">

      <xs:element name="ScaleMatrix">
        <xs:complexType>
          <xs:attribute name="Scale" type="Vector3" />
        </xs:complexType>
      </xs:element>

      <xs:element name="TranslationMatrix">
        <xs:complexType>
          <xs:attribute name="Translation" type="Vector3" />
        </xs:complexType>
      </xs:element>

    </xs:choice>
  </xs:complexType>

  <!-- Cameras -->
  <xs:complexType name="PerspectiveCamera">
    <xs:attribute name="Position" type="Vector3" use="required" />
    <xs:attribute name="LookAt" type="Vector3" use="required" />
    <xs:attribute name="Up" type="Vector3" use="required" />
    <xs:attribute name="ScreenWidth" type="xs:int" use="required" />
    <xs:attribute name="ScreenHeight" type="xs:int" use="required" />
    <xs:attribute name="FieldOfView" type="xs:float" use="required" />
  </xs:complexType>

  <xs:complexType name="OrthographicCamera">
    <xs:attribute name="Position" type="Vector3" use="required" />
    <xs:attribute name="LookAt" type="Vector3" use="required" />
    <xs:attribute name="Up" type="Vector3" use="required" />
    <xs:attribute name="ScreenWidth" type="xs:int" use="required" />
    <xs:attribute name="ScreenHeight" type="xs:int" use="required" />
    <xs:attribute name="OrthoWidth" type="xs:float" use="required" />
    <xs:attribute name="OrthoHeight" type="xs:float" use="required" />
  </xs:complexType>

  <!-- Materials -->
  <xs:group name="GroupOfMaterials">
    <xs:choice>
      <xs:element name="BasicMaterial" type="BasicMaterial" />
      <xs:element name="LuaMaterial" type="LuaMaterial" />
    </xs:choice>
  </xs:group>

  <xs:complexType name="MaterialBase">
    <xs:attribute name="Name" type="Name" />
    <xs:attribute name="AmbientCoefficient" type="xs:float" />
    <xs:attribute name="DiffuseCoefficient" type="xs:float" />
    <xs:attribute name="SpecularCoefficient" type="xs:float" />
    <xs:attribute name="ReflectionCoefficient" type="xs:float" />
    <xs:attribute name="RefractionCoefficient" type="xs:float" />
    <xs:attribute name="SpecularPower" type="xs:float" />
    <xs:attribute name="RefractionIndex" type="xs:float" />
    <xs:attribute name="LightOccluder" type="xs:boolean" />
    <xs:attribute name="ShadowReceiver" type="xs:boolean" />
  </xs:complexType>

  <xs:complexType name="BasicMaterial">
    <xs:complexContent>
      <xs:extension base="MaterialBase">
        <xs:attribute name="Color" type="Color3" />
        <xs:attribute name="SpecularColor" type="Color3" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="LuaMaterial">
    <xs:complexContent>
      <xs:extension base="MaterialBase">
        <xs:choice>
          <xs:element name="LuaCode" type="xs:string" />
        </xs:choice>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <!-- Lights -->
  <xs:complexType name="Light" abstract="true">
    <xs:attribute name="Name" type="Name" />
  </xs:complexType>

  <xs:complexType name="PointLight">
    <xs:complexContent>
      <xs:extension base="Light">
        <xs:attribute name="Color" type="Color3" use="required" />
        <xs:attribute name="Position" type="Vector3" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="DirectionalLight">
    <xs:complexContent>
      <xs:extension base="Light">
        <xs:attribute name="Direction" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <!-- Surfaces -->
  <xs:group name="GroupOfSurfaces">
    <xs:choice>
      <xs:element name="SurfaceGroup" type="SurfaceGroup" />
      <xs:element name="Csg" type="Csg" />
      <xs:element name="TransformedSurface" type="TransformedSurface" />
      <xs:element name="Plane" type="Plane" />
      <xs:element name="Sphere" type="Sphere" />
      <xs:element name="SphereSoa8" type="SphereSoa8" />
    </xs:choice>
  </xs:group>

  <xs:complexType name="SurfaceGroup">
    <xs:all>
      <xs:element name="Material" minOccurs="0">
        <xs:complexType>
          <xs:group ref="GroupOfMaterials" />
        </xs:complexType>
      </xs:element>
      <xs:element name="Surfaces" minOccurs="0">
        <xs:complexType>
          <xs:group ref="GroupOfSurfaces" maxOccurs="unbounded" />
        </xs:complexType>
      </xs:element>
    </xs:all>
    <xs:attribute name="Name" type="Name" />
    <xs:attribute name="Material" type="Name" />
  </xs:complexType>

  <xs:complexType name="Csg">
    <xs:all>
      <xs:element name="Material" minOccurs="0">
        <xs:complexType>
          <xs:group ref="GroupOfMaterials" />
        </xs:complexType>
      </xs:element>
      <xs:element name="LeftSurface">
        <xs:complexType>
          <xs:group ref="GroupOfSurfaces" />
        </xs:complexType>
      </xs:element>
      <xs:element name="RightSurface">
        <xs:complexType>
          <xs:group ref="GroupOfSurfaces" />
        </xs:complexType>
      </xs:element>
    </xs:all>
    <xs:attribute name="Name" type="Name" />
    <xs:attribute name="Material" type="Name" />
    <xs:attribute name="Operation">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="Union" />
          <xs:enumeration value="Intersection" />
          <xs:enumeration value="Difference" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="TransformedSurface">
    <xs:all>
      <xs:element name="Material" minOccurs="0">
        <xs:complexType>
          <xs:group ref="GroupOfMaterials" />
        </xs:complexType>
      </xs:element>
      <xs:element name="MatrixStack" type="MatrixStack" />
      <xs:element name="Surface">
        <xs:complexType>
          <xs:group ref="GroupOfSurfaces" />
        </xs:complexType>
      </xs:element>
    </xs:all>
    <xs:attribute name="Name" type="Name" />
    <xs:attribute name="Material" type="Name" />
  </xs:complexType>

  <xs:complexType name="Plane">
    <xs:all>
      <xs:element name="Material" minOccurs="0">
        <xs:complexType>
          <xs:group ref="GroupOfMaterials" />
        </xs:complexType>
      </xs:element>
    </xs:all>
    <xs:attribute name="Name" type="Name" />
    <xs:attribute name="Material" type="Name" />
    <xs:attribute name="Normal" type="Vector3" />
    <xs:attribute name="Point" type="Vector3" />
  </xs:complexType>

  <xs:complexType name="Sphere">
    <xs:all>
      <xs:element name="Material" minOccurs="0">
        <xs:complexType>
          <xs:group ref="GroupOfMaterials" />
        </xs:complexType>
      </xs:element>
    </xs:all>
    <xs:attribute name="Name" type="Name" />
    <xs:attribute name="Material" type="Name" />
    <xs:attribute name="Center" type="Vector3" />
    <xs:attribute name="Radius" type="xs:float" />
  </xs:complexType>

  <xs:complexType name="SphereSoa8">
    <xs:all>
      <xs:element name="Spheres" minOccurs="1">
        <xs:complexType>
          <xs:choice minOccurs="8" maxOccurs="8">
            <xs:element name="Sphere" type="Sphere" />
          </xs:choice>
        </xs:complexType>
      </xs:element>
    </xs:all>
    <xs:attribute name="Name" type="Name" />
  </xs:complexType>

</xs:schema>

=== jorgy343/NovahTracer/Source/Novah.Tracer.Client/Scenes/CsgScene.xml
<?xml version="1.0" encoding="utf-8"?>
<Scene xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
       xsi:noNamespaceSchemaLocation="Scene.xsd"
       BackgroundColor="0,0,0"
       DefaultRefractionIndex="1"
       AntialiasingLevel="4">
  <Camera>
    <PerspectiveCamera Position="-13,30,-50" LookAt="0,12,0" Up="0,1,0" ScreenWidth="1600" ScreenHeight="900" FieldOfView="1.57079633" />
  </Camera>
  <Materials>
    <BasicMaterial Name="Red"
              Color="1,0,0"
              SpecularColor="1,1,1"
              AmbientCoefficient="0.1"
              DiffuseCoefficient="0.9"
              SpecularCoefficient="0"
              ReflectionCoefficient="0"
              RefractionCoefficient="0"
              SpecularPower="0"
              RefractionIndex="1"
              LightOccluder="true"
              ShadowReceiver="true" />
    <BasicMaterial Name="Green"
              Color="0,1,0"
              SpecularColor="1,1,1"
              AmbientCoefficient="0.1"
              DiffuseCoefficient="0.9"
              SpecularCoefficient="0"
              ReflectionCoefficient="0"
              RefractionCoefficient="0"
              SpecularPower="0"
              RefractionIndex="1"
              LightOccluder="true"
              ShadowReceiver="true" />
    <BasicMaterial Name="Blue"
              Color="0,0,1"
              SpecularColor="1,1,1"
              AmbientCoefficient="0.1"
              DiffuseCoefficient="0.9"
              SpecularCoefficient="0"
              ReflectionCoefficient="0"
              RefractionCoefficient="0"
              SpecularPower="0"
              RefractionIndex="1"
              LightOccluder="true"
              ShadowReceiver="true" />
    <BasicMaterial Name="Metalic"
              Color="1,1,1"
              SpecularColor="1,1,1"
              AmbientCoefficient="0.1"
              DiffuseCoefficient="0.5"
              SpecularCoefficient="0.5"
              ReflectionCoefficient="0.5"
              RefractionCoefficient="0"
              SpecularPower="100"
              RefractionIndex="1"
              LightOccluder="true"
              ShadowReceiver="true" />
  </Materials>
  <Lights>
    <PointLight Color="1,1,1" Position="43,43,13" />
  </Lights>
  <RootSurface>
    <SurfaceGroup>
      <Surfaces>
        <Csg Operation="Difference">
          <LeftSurface>
            <Csg Operation="Intersection">
              <LeftSurface>
                <AxisAlignedRectangularBox Material="Red" Minimum="-10,5,-10" Maximum="10,25,10" />
              </LeftSurface>
              <RightSurface>
                <Sphere Material="Blue" Center="0,15,0" Radius="14" />
              </RightSurface>
            </Csg>
          </LeftSurface>
          <RightSurface>
            <Sphere Material="Green" Center="0,15,0" Radius="13" />
          </RightSurface>
        </Csg>
      </Surfaces>
    </SurfaceGroup>
  </RootSurface>
</Scene>

=== jorgy343/NovahTracer/Source/Novah.Tracer.Client/Scenes/LensScene.xml
<?xml version="1.0" encoding="utf-8"?>
<Scene xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
       xsi:noNamespaceSchemaLocation="Scene.xsd"
       BackgroundColor="0,0,0"
       DefaultRefractionIndex="1"
       AntialiasingLevel="4">
  <Camera>
    <PerspectiveCamera Position="-30,20,-39" LookAt="-3,-6,0" Up="0,1,0" ScreenWidth="1600" ScreenHeight="900" FieldOfView="1.57079633" />
  </Camera>
  <Materials>
    <BasicMaterial Name="Red"
              Color="1,0,0"
              SpecularColor="1,1,1"
              AmbientCoefficient="0.1"
              DiffuseCoefficient="0.9"
              SpecularCoefficient="0"
              ReflectionCoefficient="0"
              RefractionCoefficient="0"
              SpecularPower="0"
              RefractionIndex="1"
              LightOccluder="true"
              ShadowReceiver="true" />
    <BasicMaterial Name="Green"
              Color="0,1,0"
              SpecularColor="1,1,1"
              AmbientCoefficient="0.1"
              DiffuseCoefficient="0.9"
              SpecularCoefficient="0"
              ReflectionCoefficient="0"
              RefractionCoefficient="0"
              SpecularPower="0"
              RefractionIndex="1"
              LightOccluder="true"
              ShadowReceiver="true" />
    <BasicMaterial Name="Blue"
              Color="0,0,1"
              SpecularColor="1,1,1"
              AmbientCoefficient="0.1"
              DiffuseCoefficient="0.9"
              SpecularCoefficient="0"
              ReflectionCoefficient="0"
              RefractionCoefficient="0"
              SpecularPower="0"
              RefractionIndex="1"
              LightOccluder="true"
              ShadowReceiver="true" />
    
    <BasicMaterial Name="Metalic"
              Color="1,1,1"
              SpecularColor="1,1,1"
              AmbientCoefficient="0.1"
              DiffuseCoefficient="0.5"
              SpecularCoefficient="0.5"
              ReflectionCoefficient="0.5"
              RefractionCoefficient="0"
              SpecularPower="100"
              RefractionIndex="1"
              LightOccluder="true"
              ShadowReceiver="true" />
    <BasicMaterial Name="Lens"
              Color="1,1,1"
              SpecularColor="1,1,1"
              AmbientCoefficient="0.0"
              DiffuseCoefficient="0.0"
              SpecularCoefficient="0.5"
              ReflectionCoefficient="1.0"
              RefractionCoefficient="1.0"
              SpecularPower="200"
              RefractionIndex="1.5"
              LightOccluder="false"
              ShadowReceiver="false" />

    <LuaMaterial Name="RedChecker"
                 AmbientCoefficient="0.1"
                 DiffuseCoefficient="0.9"
                 SpecularCoefficient="0"
                 ReflectionCoefficient="0"
                 RefractionCoefficient="0"
                 SpecularPower="0"
                 RefractionIndex="1"
                 LightOccluder="false"
                 ShadowReceiver="true">
      <LuaCode>
        <![CDATA[
        
        function shade(point, normal)
            local x = math.abs(math.floor((point.X) / 5.0));
            local y = math.abs(math.floor((point.Y) / 5.0));
    
            local xmod = x % 2;
            local ymod = y % 2;
    
            if xmod == ymod then
                return { Red = 1.0, Green = 0.4, Blue = 0.4 };
            else
                return { Red = 1.0, Green = 1.0, Blue = 1.0 };
            end
        end

        ]]>
      </LuaCode>
    </LuaMaterial>

    <LuaMaterial Name="GreenChecker"
              AmbientCoefficient="0.1"
              DiffuseCoefficient="0.9"
              SpecularCoefficient="0"
              ReflectionCoefficient="0"
              RefractionCoefficient="0"
              SpecularPower="0"
              RefractionIndex="1"
              LightOccluder="false"
              ShadowReceiver="true">
      <LuaCode>
        <![CDATA[
        
        function shade(point, normal)
            local z = math.abs(math.floor((point.Z) / 5.0));
            local y = math.abs(math.floor((point.Y) / 5.0));
    
            local zmod = z % 2;
            local ymod = y % 2;
    
            if zmod == ymod then
                return { Red = 0.2, Green = 0.8, Blue = 0.2 };
            else
                return { Red = 1.0, Green = 1.0, Blue = 1.0 };
            end
        end

        ]]>
      </LuaCode>
    </LuaMaterial>
    
    <LuaMaterial Name="BlueChecker"
              AmbientCoefficient="0.1"
              DiffuseCoefficient="0.9"
              SpecularCoefficient="0"
              ReflectionCoefficient="0"
              RefractionCoefficient="0"
              SpecularPower="0"
              RefractionIndex="1"
              LightOccluder="false"
              ShadowReceiver="true">
      <LuaCode>
        <![CDATA[
        
        function shade(point, normal)
            local z = math.abs(math.floor((point.Z) / 5.0));
            local x = math.abs(math.floor((point.X) / 5.0));
    
            local zmod = z % 2;
            local xmod = x % 2;
    
            if zmod == xmod then
                return { Red = 0.4, Green = 0.4, Blue = 1.0 };
            else
                return { Red = 1.0, Green = 1.0, Blue = 1.0 };
            end
        end

        ]]>
      </LuaCode>
    </LuaMaterial>
  </Materials>
  <Lights>
    <!--<PointLight Color="1,1,1" Position="-15,13,-35" />-->
    <ParallelogramLight Color="1,1,1" Corner="-15,13,-35" Edge1="0,5,0" Edge2="5,0,0" SampleLevel="10" SampleMode="2" />
  </Lights>
  <RootSurface>
    <SurfaceGroup>
      <Surfaces>
        <Sphere Material="Metalic" Center="-30,-30,+30" Radius="5" />
        <Sphere Material="Metalic" Center="-15,-30,+30" Radius="5" />
        <Sphere Material="Metalic" Center="+00,-30,+30" Radius="5" />
        <Sphere Material="Metalic" Center="+15,-30,+30" Radius="5" />
        <Sphere Material="Metalic" Center="+30,-30,+30" Radius="5" />
        
        <Sphere Material="Metalic" Center="-30,-15,+25" Radius="5" />
        <Sphere Material="Metalic" Center="-15,-15,+25" Radius="6" />
        <Sphere Material="Metalic" Center="+00,-15,+25" Radius="6" />
        <Sphere Material="Metalic" Center="+15,-15,+25" Radius="6" />
        <Sphere Material="Metalic" Center="+30,-15,+25" Radius="5" />
        
        <Sphere Material="Metalic" Center="-30,-00,+20" Radius="5" />
        <Sphere Material="Metalic" Center="-15,-00,+20" Radius="6" />
        <Sphere Material="Metalic" Center="+00,-00,+20" Radius="7" />
        <Sphere Material="Metalic" Center="+15,-00,+20" Radius="6" />
        <Sphere Material="Metalic" Center="+30,-00,+20" Radius="5" />
        
        <Sphere Material="Metalic" Center="-30,+15,+25" Radius="5" />
        <Sphere Material="Metalic" Center="-15,+15,+25" Radius="6" />
        <Sphere Material="Metalic" Center="+00,+15,+25" Radius="6" />
        <Sphere Material="Metalic" Center="+15,+15,+25" Radius="6" />
        <Sphere Material="Metalic" Center="+30,+15,+25" Radius="5" />
        
        <Sphere Material="Metalic" Center="-30,+30,+30" Radius="5" />
        <Sphere Material="Metalic" Center="-15,+30,+30" Radius="5" />
        <Sphere Material="Metalic" Center="+00,+30,+30" Radius="5" />
        <Sphere Material="Metalic" Center="+15,+30,+30" Radius="5" />
        <Sphere Material="Metalic" Center="+30,+30,+30" Radius="5" />

        <Csg Operation="Intersection">
          <LeftSurface>
            <TransformedSurface>
              <MatrixStack>
                <TranslationMatrix Translation="-23,13,-27" />
                <ScaleMatrix Scale="1,1,0.07" />
              </MatrixStack>
              <Surface>
                <Sphere Material="Lens" Center="0,0,0" Radius="7" />
              </Surface>
            </TransformedSurface>
          </LeftSurface>
          <RightSurface>
            <Sphere Material="Lens" Center="-23,13,-27" Radius="5" />
          </RightSurface>
        </Csg>

        <Plane Name="Floor" Material="BlueChecker" Normal="0,1,0" Point="0,-40,0" />
        <Plane Name="Ceiling" Material="BlueChecker" Normal="0,-1,0" Point="0,40,0" />
        <Plane Name="FarWall" Material="RedChecker" Normal="0,0,-1" Point="0,0,40" />
        <Plane Name="NearWall" Material="RedChecker" Normal="0,0,1" Point="0,0,-40" />
        <Plane Name="LeftWall" Material="GreenChecker" Normal="1,0,0" Point="-40,0,0" />
        <Plane Name="RightWall" Material="GreenChecker" Normal="-1,0,0" Point="40,0,0" />
      <!--
        <Csg Operation="Difference">
          <LeftSurface>
            <Csg Operation="Intersection">
              <LeftSurface>
                <AxisAlignedRectangularBox Material="Red" Minimum="-10,5,-10" Maximum="10,25,10" />
              </LeftSurface>
              <RightSurface>
                <Sphere Material="Blue" Center="0,15,0" Radius="14" />
              </RightSurface>
            </Csg>
          </LeftSurface>
          <RightSurface>
            <Sphere Material="Green" Center="0,15,0" Radius="13" />
          </RightSurface>
        </Csg>-->
      </Surfaces>
    </SurfaceGroup>
  </RootSurface>
</Scene>
